TrajectoryPlannerROS:
  max_vel_x: 0.5 #11.30
  min_vel_x: 0.01
  max_vel_theta: 0.5
  min_vel_theta: 0.005
  min_in_place_vel_theta : 0.1
  min_in_vel_rotational_vel: 0.1
  min_in_place_rotational_vel: 0.01

  acc_lim_th: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  holonomic_robot: false
